/**
 * > **GOS3** · agente: `claude` · papel: `Arquiteto / Tech Writer` (ver docs/team.md)
 * > fase: `fase 5 — padronização e governança de especificações` · data: `2026-08-21` · hora: `18:10:00 UTC`
 * > antes: Conectores dispersos e sem suporte unificado ao sandbox Google Colab/GCloud
 * > depois: Catálogo completo de conectores externos estilo Grok (Google Workspace, Colab, GCloud, GitHub, Stripe, Notion, Canva, Box, Wix, Calendly, n8n) com ativação de runtime CLI/GUI
 * > base: commit `gos3-core-v1.0`, docs/GOS3-SPECIFICATION.md
 * > assinatura: `Claude · Arquiteto / Tech Writer · GOS3`
 */

import { ExternalConnector } from "../types";

export const INITIAL_CONNECTORS: ExternalConnector[] = [
  {
    id: "gmail",
    name: "Gmail",
    category: "google",
    description: "Pesquisa, leitura e despacho de e-mails em tempo real via Google Workspace API.",
    iconType: "gmail",
    color: "#EA4335",
    badge: "Google",
    isConnected: true,
    isGoogleEcosystem: true,
    enablesSandbox: false,
    authRequired: true,
    accountEmail: "sobrinhoSJ@gmail.com",
    connectedAt: "2026-08-21 14:00:00",
    capabilities: ["Ler mensagens", "Rascunhar e-mails", "Filtrar threads por assunto"],
  },
  {
    id: "calendar",
    name: "Google Calendar",
    category: "google",
    description: "Sincronização de agendas de reuniões, sprints de agentes e deliberações 1xN.",
    iconType: "calendar",
    color: "#4285F4",
    badge: "Google",
    isConnected: true,
    isGoogleEcosystem: true,
    enablesSandbox: false,
    authRequired: true,
    accountEmail: "sobrinhoSJ@gmail.com",
    connectedAt: "2026-08-21 14:00:00",
    capabilities: ["Criar eventos", "Consultar disponibilidade", "Lembretes GOS3"],
  },
  {
    id: "drive",
    name: "Google Drive",
    category: "google",
    description: "Acesso a documentos, planilhas e anexos compartilhados diretamente com os agentes.",
    iconType: "drive",
    color: "#34A853",
    badge: "Google",
    isConnected: true,
    isGoogleEcosystem: true,
    enablesSandbox: false,
    authRequired: true,
    accountEmail: "sobrinhoSJ@gmail.com",
    connectedAt: "2026-08-21 14:00:00",
    capabilities: ["Download de arquivos", "Indexação vetorial", "Exportação de relatórios"],
  },
  {
    id: "gcolab",
    name: "Google Colab (Sandbox Runtime)",
    category: "google",
    description: "Runtime Jupyter / Python interativo com aceleração GPU (T4/V100) habilitado no chat em modo CLI ou GUI full.",
    iconType: "colab",
    color: "#F9AB00",
    badge: "Google Sandbox",
    isConnected: true,
    isGoogleEcosystem: true,
    enablesSandbox: true,
    authRequired: true,
    accountEmail: "sobrinhoSJ@gmail.com",
    connectedAt: "2026-08-21 14:00:00",
    capabilities: ["Execução Python Interativa", "Jupyter Notebook GUI no Chat", "Shell CLI direto", "Aceleração GPU / PyTorch"],
  },
  {
    id: "gcloud",
    name: "Google Cloud SDK & Run",
    category: "google",
    description: "Container runtime, Cloud Functions, Cloud SQL e deployment em Cloud Run com CLI e console visual integrado.",
    iconType: "gcloud",
    color: "#4285F4",
    badge: "Google Cloud",
    isConnected: true,
    isGoogleEcosystem: true,
    enablesSandbox: true,
    authRequired: true,
    accountEmail: "sobrinhoSJ@gmail.com",
    connectedAt: "2026-08-21 14:00:00",
    capabilities: ["gcloud CLI terminal", "Cloud Run deployments", "Monitoramento de métricas", "Storage buckets"],
  },
  {
    id: "canva",
    name: "Canva",
    category: "destaques",
    description: "Geração de artes, diagramas e banners vetoriais a partir dos prompts de agentes.",
    iconType: "canva",
    color: "#7D2AE8",
    badge: "Design",
    isConnected: false,
    authRequired: true,
    capabilities: ["Exportar designs", "Gerar templates dinâmicos", "Assets visuais"],
  },
  {
    id: "github",
    name: "GitHub",
    category: "desenvolvimento",
    description: "Envio de repositórios, clonagem de árvores de arquivos, PRs automáticos e code reviews ao mencionar @agentes.",
    iconType: "github",
    color: "#FFFFFF",
    badge: "Código & Repos",
    isConnected: true,
    authRequired: true,
    accountEmail: "sobrinhoSJ (GitHub OAuth)",
    connectedAt: "2026-08-21 12:30:00",
    capabilities: ["Anexar Repositórios aos Agentes", "Inspeção profunda de AST", "Commit & PRs", "GOS3 audit"],
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "destaques",
    description: "Processamento de pagamentos, cobrança de tokens DREX e checkout de planos Pro/Enterprise.",
    iconType: "stripe",
    color: "#635BFF",
    badge: "Fintech",
    isConnected: false,
    authRequired: true,
    capabilities: ["Assinaturas recorrentes", "Webhooks de pagamento", "Recargas de DREX"],
  },
  {
    id: "notion",
    name: "Notion",
    category: "produtividade",
    description: "Bases de conhecimento estruturadas, atas de reuniões GOS3 e documentação wiki.",
    iconType: "notion",
    color: "#FFFFFF",
    badge: "Knowledge Base",
    isConnected: false,
    authRequired: true,
    capabilities: ["Criar páginas", "Consultar bancos de dados", "Sincronização bidirecional"],
  },
  {
    id: "box",
    name: "Box",
    category: "produtividade",
    description: "Armazenamento em nuvem corporativo com controle granular de acesso.",
    iconType: "box",
    color: "#0061D5",
    badge: "Cloud Storage",
    isConnected: false,
    authRequired: true,
    capabilities: ["Upload seguro", "Versionamento", "Permissões enterprise"],
  },
  {
    id: "wix",
    name: "Wix",
    category: "destaques",
    description: "Criação de landing pages e publicação de sites estáticos gerados por agentes.",
    iconType: "wix",
    color: "#0C0C0D",
    badge: "Web CMS",
    isConnected: false,
    authRequired: true,
    capabilities: ["Publicação web", "Gerenciamento de domínios", "Templates"],
  },
  {
    id: "calendly",
    name: "Calendly",
    category: "produtividade",
    description: "Agendamento automático de chamadas com agentes e especialistas humanos.",
    iconType: "calendly",
    color: "#006BFF",
    badge: "Agendamento",
    isConnected: false,
    authRequired: true,
    capabilities: ["Verificar horários livres", "Criar links dinâmicos de agendamento"],
  },
  {
    id: "firebase",
    name: "Firebase (Firestore & Auth)",
    category: "google",
    description: "Banco de dados Firestore corporativo e autenticação OAuth oficial provisionados no projeto Google Cloud gen-lang-client-0100483792.",
    iconType: "firebase",
    color: "#FFCA28",
    badge: "Cloud DB & Auth",
    isConnected: true,
    isGoogleEcosystem: true,
    enablesSandbox: true,
    authRequired: true,
    accountEmail: "sobrinhoSJ@gmail.com (Firebase Enterprise)",
    connectedAt: "2026-08-22 07:01:00",
    capabilities: ["Firestore NoSQL Database", "Zero-Trust Security Rules (ABAC)", "Google Auth", "Sub-ms Query Indexing"],
  },
  {
    id: "gaistudio",
    name: "Google AI Studio (GAIStudio Engine)",
    category: "google",
    description: "Conexão oficial com a conta Google ativa no GAIStudio para modelos Gemini 2.5/3.7, Live Multimodal API e orquestração de agentes.",
    iconType: "gaistudio",
    color: "#4285F4",
    badge: "GAIStudio Ativo",
    isConnected: true,
    isGoogleEcosystem: true,
    enablesSandbox: true,
    authRequired: true,
    accountEmail: "sobrinhoSJ@gmail.com (Conta Google Ativa)",
    connectedAt: "2026-08-21 14:00:00",
    capabilities: ["Gemini 3.7 Pro / Flash", "Function Calling Nativo", "Zero-Token Grounding", "Associação com Cloud Run"],
  },
  {
    id: "custom_vps_vm",
    name: "VPS / VM / Android Termux (A23)",
    category: "desenvolvimento",
    description: "Conector de Sandbox Runtime externo para VPS (Linux/Docker), VM Free/Paga ou Android Termux (Samsung A23) com ramdisk dedicada.",
    iconType: "vps",
    color: "#10B981",
    badge: "Runtime Externo",
    isConnected: true,
    enablesSandbox: true,
    authRequired: false,
    accountEmail: "Termux @ A23 / VPS Local Node Sandbox",
    connectedAt: "2026-08-21 15:30:00",
    capabilities: ["Execução em Celular Android A23", "Ramdisk isolada na VM", "SSH / Shell Linux Remoto", "Subprocessos de Baixa Latência"],
  },
  {
    id: "n8n",
    name: "n8n Automation Bridge",
    category: "automacao",
    description: "Ponte de automação de webhooks em tempo real conectando chat, voz e centenas de nós.",
    iconType: "n8n",
    color: "#EA4B71",
    badge: "Automação",
    isConnected: true,
    authRequired: false,
    connectedAt: "2026-08-21 14:00:00",
    capabilities: ["Webhooks em tempo real", "Disparo de voz 1xN", "Workflows multi-serviço"],
  },
];
